In [1]:
import pandas as pd
import numpy as np

In [4]:
from google.colab import files
uploaded = files.upload()

Saving sale.csv to sale.csv


In [5]:
dataset = pd.read_csv('sale.csv')
print(dataset)

    Age  Salary  Status
0    18   25000       0
1    24   24000       1
2    33   12000       1
3    45   28000       0
4    21   85000       0
..  ...     ...     ...
94   38   25200       1
95   23   78400       0
96   41   34500       0
97   46   51000       0
98   34   28000       1

[99 rows x 3 columns]


In [6]:
print(dataset.shape)
print(dataset.head(5))

(99, 3)
   Age  Salary  Status
0   18   25000       0
1   24   24000       1
2   33   12000       1
3   45   28000       0
4   21   85000       0


In [7]:
X = dataset.iloc[:,:-1].values
X

array([[   18, 25000],
       [   24, 24000],
       [   33, 12000],
       [   45, 28000],
       [   21, 85000],
       [   23, 91000],
       [   34, 22000],
       [   54, 52000],
       [   33, 43000],
       [   23, 25000],
       [   43, 44000],
       [   54, 25000],
       [   42, 29000],
       [   19, 55000],
       [   25, 67000],
       [   35, 25000],
       [   27, 76000],
       [   29, 91000],
       [   30, 23000],
       [   34, 53000],
       [   52, 28000],
       [   22, 20000],
       [   34, 25700],
       [   21, 62000],
       [   22, 84000],
       [   54, 19000],
       [   34, 25000],
       [   55, 57000],
       [   50, 54000],
       [   24, 28000],
       [   26, 15000],
       [   29, 26000],
       [   42, 25000],
       [   19, 76000],
       [   25, 91000],
       [   35, 23000],
       [   27, 53000],
       [   29, 28000],
       [   30, 20000],
       [   34, 25700],
       [   52, 62000],
       [   22, 84000],
       [   18, 25000],
       [   

In [8]:
Y = dataset.iloc[:,-1]
Y

0     0
1     1
2     1
3     0
4     0
     ..
94    1
95    0
96    0
97    0
98    1
Name: Status, Length: 99, dtype: int64

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.25,random_state=0)

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)

[[ 0.08937387 -0.83524771]
 [ 0.08937387 -0.96927372]
 [ 0.08937387 -0.70122169]
 [ 0.84522148 -0.52252034]
 [-0.94991659  0.90709048]
 [-1.3278404   0.50501244]
 [ 0.93970244 -0.87992305]
 [-1.42232135  0.81773981]
 [ 0.08937387 -0.96927372]
 [-0.94991659  1.0411165 ]
 [ 2.07347385  0.59436311]
 [-0.28854993 -0.92459838]
 [-0.76095469 -0.03109162]
 [-0.09958803  1.0411165 ]
 [ 1.12866434  0.86241514]
 [-0.85543564 -0.87992305]
 [-1.42232135 -0.38849433]
 [-1.42232135 -0.83524771]
 [-1.04439754  1.80059725]
 [-1.1388785   1.84527258]
 [ 0.18385482 -0.83524771]
 [-0.38303088  2.11332461]
 [ 1.790031    0.81773981]
 [-0.28854993 -1.0586244 ]
 [-0.94991659  2.11332461]
 [ 0.27833578 -0.92459838]
 [ 0.18385482  1.44319454]
 [-1.42232135 -0.83524771]
 [-0.76095469  2.11332461]
 [ 1.6010691   0.4603371 ]
 [-0.00510708  0.50501244]
 [ 1.9789929  -0.83524771]
 [ 0.18385482 -0.92459838]
 [-1.1388785   0.81773981]
 [ 0.93970244 -0.83524771]
 [ 0.93970244  0.01358372]
 [-0.38303088 -0.79057237]
 

In [15]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train,Y_train)

LogisticRegression()

In [20]:
age = int(input("enter the customers age: "))
sal = int(input("enter the customers salary: "))
newCust = [[age,sal]]
result = model.predict(sc.transform(newCust))
print(result)
if result == 1 :
  print("Customer will buy")
else:
  print("Customer will not buy")

enter the customers age: 43
enter the customers salary: 44000
[0]
Customer will not buy


In [18]:
y_pred = model.predict(X_test)

In [19]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(Y_test,y_pred)
print("Confusion matrix: ")
print(cm)
print("Accuracy of the model ; {0}% ".format(accuracy_score(Y_test,y_pred)*100))

Confusion matrix: 
[[ 9  1]
 [13  2]]
Accuracy of the model ; 44.0% 
